### PR TITLE
build: deno support with denoify

### LINKED ISSUE #9: deno support
hi, thanks for the adapter support. however it doesn't seem to play nicely with [deno version of hono](deno.land/x/hono@v3.4.0/); there seems to be a conflict between generated types.

```ts
$ deno check backend/main.ts file:///home/scarf/repo/lib42/backend/v2/backend/main.ts
error: TS2345 [ERROR]: Argument of type 'Hono<HonoEnv, {}, "/">' is not assignable to parameter of type 'Hono<any, any, "">'.
  The types of 'router.add' are incompatible between these types.
    Type '(method: string, path: string, handler: import("https://deno.land/x/hono@v3.4.0/types.ts").H) => void' is not assignable to type '(method: string, path: string, handler: import("file:///home/scarf/.cache/deno/npm/registry.npmjs.org/hono/3.4.0/dist/types/types.d.ts").H) => void'.
      Types of parameters 'handler' and 'handler' are incompatible.
        Type 'import("file:///home/scarf/.cache/deno/npm/registry.npmjs.org/hono/3.4.0/dist/types/types.d.ts").H' is not assignable to type 'import("https://deno.land/x/hono@v3.4.0/types.ts").H'.
          Type 'Handler<any, any, {}, {}>' is not assignable to type 'H'.
            Type 'import("file:///home/scarf/.cache/deno/npm/registry.npmjs.org/hono/3.4.0/dist/types/types.d.ts").Handler<any, any, {}, {}>' is not assignable to type 'import("https://deno.land/x/hono@v3.4.0/types.ts").Handler<any, any, {}, {}>'.
              Types of parameters 'c' and 'c' are incompatible.
                Type 'import("https://deno.land/x/hono@v3.4.0/context.ts").Context<any, any, {}>' is not assignable to type 'import("file:///home/scarf/.cache/deno/npm/registry.npmjs.org/hono/3.4.0/dist/types/context.d.ts").Context<any, any, {}>'.
                  Types have separate declarations of a private property '_req'.
createHonoEndpoints(contract, router, app, {
                                      ~~~
```

It'd be really great if ts-rest-hono could support deno as well. I believe this could be achieved by using [denoify](https://www.denoify.land) like [hono](https://github.com/honojs/hono/blob/a104bf0010ba24cc2b23a13ac1070a199f2a9fcb/package.json#L25). I'm interested in opening a PR.

### PR DESCRIPTION
**Pull request by scarf005**
- blocked by #10 , #13
- resolves #9 

I've explicitly committed `deno_dist` directory following github.com/honojs/hono. By [adding webhooks to deno 3rd party packages repository](https://docs.denoify.land/publishing-on-deno.land-x), this package could also be served from <https://deno.land/x>.

### CODE REVIEW

**Review by msutkowski — COMMENTED** [review]
@scarf005 I know roughly 0 things about denoify :). Does the denoify step need to be a part of a build step on publish, or does this just magically work as-is?

**Comment by scarf005** [comment]
it could be either
- automated using workflow (i.e push to `deno` branch) to keep commit history clean, takes some work
- or be ran and updated manually using `npm run denoify` command.

**Comment by msutkowski** [comment]
> it could be either
> 
> * automated using workflow (i.e push to `deno` branch) to keep commit history clean, takes some work
> * or be ran and updated manually using `npm run denoify` command.

Yea, looking through the example here - https://github.com/garronej/my_dummy_npm_and_deno_module, there is a little more that could be done re: tsconfig, setting `"build": "pkgroll && denoify"`, etc etc. I'm assuming it makes sense to build + publish to deno.land as a part of the normal build step? I'd be happy to just throw the publish step in CI, but could use help with any of the deno parts =)

**Comment by msutkowski** [comment]
> github.com/honojs/hono

Yea, we can just do what hono does and that should be fine - https://github.com/honojs/hono/blob/main/package.json#L27-L33. If you're on discord and would like to chat about this quickly, my username is the same (msutkowski). I'd like to get this + the other open PR in and update docs + cut a release today.

**Review by msutkowski — APPROVED** [review]

**Pull request merged**
